import { getToken } from './auth.js';

async function apiFetch(url, options = {}) {
  const token = await getToken();
  const res = await fetch(url, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || `API error ${res.status}`);
  }
  if (res.status === 204) return null;
  return res.json();
}

export async function getMe() {
  return apiFetch('https://api.spotify.com/v1/me');
}

const LANGUAGE_KEYWORDS = {
  hindi:      'hindi',
  tamil:      'tamil',
  telugu:     'telugu',
  kannada:    'kannada',
  malayalam:  'malayalam',
  bengali:    'bengali',
  punjabi:    'punjabi',
  marathi:    'marathi',
  english:    'english',
  spanish:    'spanish',
  korean:     'korean',
  japanese:   'japanese',
  french:     'french',
  portuguese: 'portuguese',
  arabic:     'arabic',
  italian:    'italian',
};

// Market codes narrow results to tracks available (and popular) in that region
const LANGUAGE_MARKETS = {
  hindi:      'IN',
  tamil:      'IN',
  telugu:     'IN',
  kannada:    'IN',
  malayalam:  'IN',
  bengali:    'IN',
  punjabi:    'IN',
  marathi:    'IN',
  english:    'US',
  spanish:    'ES',
  korean:     'KR',
  japanese:   'JP',
  french:     'FR',
  portuguese: 'BR',
  arabic:     'SA',
  italian:    'IT',
};

export async function getRecommendations(_mood, seedGenres, languages = []) {
  // /v1/recommendations was deprecated Nov 2024; use search with genre + language combinations
  const langEntries = languages.length > 0
    ? languages
        .map(l => ({ term: LANGUAGE_KEYWORDS[l], market: LANGUAGE_MARKETS[l] }))
        .filter(e => e.term)
    : [{ term: '', market: null }];

  const queries = [];
  for (const genre of seedGenres) {
    for (const { term, market } of langEntries) {
      // Language term first so Spotify weights it higher than genre
      queries.push({ q: term ? `${term} ${genre}` : genre, market });
    }
  }

  const results = await Promise.allSettled(
    queries.map(({ q, market }) => {
      const params = { q, type: 'track', limit: '10' };
      if (market) params.market = market;
      const query = new URLSearchParams(params);
      return apiFetch(`https://api.spotify.com/v1/search?${query}`);
    })
  );

  const seen = new Set();
  const tracks = results
    .filter(r => r.status === 'fulfilled')
    .flatMap(r => r.value.tracks.items)
    .filter(t => {
      if (seen.has(t.id)) return false;
      seen.add(t.id);
      return true;
    });

  if (tracks.length === 0) throw new Error('No tracks found. Try a different mood or language.');
  return { tracks: tracks.sort(() => Math.random() - 0.5) };
}

const MOOD_GENRES = {
  happy:     ['pop', 'dance', 'indie pop'],
  energetic: ['hip hop', 'electronic', 'workout'],
  chill:     ['chill', 'lofi', 'ambient'],
  sad:       ['sad', 'indie', 'singer songwriter'],
  romantic:  ['romantic', 'soul', 'rnb'],
};

export function getMoodGenres(mood) {
  return MOOD_GENRES[mood] || ['pop'];
}

export async function createPlaylist(_userId, mood, tracks, customName = null) {
  const moodLabel = mood.charAt(0).toUpperCase() + mood.slice(1);
  const name = customName || `Wavelength — ${moodLabel} Vibes`;

  // POST /v1/me/playlists replaces the removed /users/{id}/playlists (Feb 2026)
  const playlist = await apiFetch('https://api.spotify.com/v1/me/playlists', {
    method: 'POST',
    body: JSON.stringify({
      name,
      description: `A ${mood} playlist generated by Wavelength`,
      public: false,
    }),
  });

  // POST /v1/playlists/{id}/items replaces the removed /tracks endpoint (Feb 2026)
  await apiFetch(`https://api.spotify.com/v1/playlists/${playlist.id}/items`, {
    method: 'POST',
    body: JSON.stringify({ uris: tracks.map(t => t.uri) }),
  });

  return playlist;
}
